### ISSUE TITLE
Weird floating point in NewRelic display

### ISSUE THREAD

**Issue by asciifaceman** [Etherhypnos/agent-haproxy-a0labs#5]
I am seeing a changing floating point showing up for # of servers in the NewRelic HAProxy page

![screenshot-21](https://cloud.githubusercontent.com/assets/1619591/13645783/83b4cef4-e5e1-11e5-8c56-668f9d63a9b0.png)

While we are able to look at this and see that obviously there aren't 8.01 servers (the floating point seems to change between 0.01 and 0.33 etc), I am worried other statistics might be affected by a similar problem - thus altering accurate results

**Comment by ybriffa** [comment]
Yeah, I was worried about it so I contacted Newrelic's support, and it appeared that's quite normal.

Apparently, when the plugin pushes values every 60s, it can be 60.00001s, depending on the clock of every servers, so this small amount of value, added and averaged over the time can be seen like you've shown.

In the first place, we wanted to use this value to put a treshold if it goes down or up (in order to know if there is a new server in the cluster or if we lost one), then the support for this reason advised us to put the treshold not exactly on the value, but a bit over and below, something like 6.8 and 7.2 for 7 normally.

Hoping  I've been clear enough, let me know if you want me to try to explain to you in other words

**Comment by asciifaceman** [comment]
Thank you for the explanation, I am fine with this.

On Wed, Mar 9, 2016 at 12:44 PM, Yannick Briffa notifications@github.com
wrote:

> Yeah, I was worried about it so I contacted Newrelic's support, and it
> appeared that's quite normal.
> 
> Apparently, when the plugin pushes values every 60s, it can be 60.00001s,
> depending on the clock of every servers, so this small amount of value,
> added and averaged over the time can be seen like you've shown.
> 
> In the first place, we wanted to use this value to put a treshold if it
> goes down or up (in order to know if there is a new server in the cluster
> or if we lost one), then the support for this reason advised us to put the
> treshold not exactly on the value, but a bit over and below, something like
> 6.8 and 7.2 for 7 normally.
> 
> Hoping I've been clear enough, let me know if you want me to try to
> explain to you in other words
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Etherhypnos/agent-haproxy-a0labs/issues/5#issuecomment-194499696
> .

## 

Charles P. Corbett
